fixing ES run

diff --git a/files/elasticsearch_run b/files/elasticsearch_run
--- a/files/elasticsearch_run
+++ b/files/elasticsearch_run
@@ -1,3 +1,97 @@
 #!/bin/sh
 
-/usr/local/bin/elasticsearch
+PATH=/bin:/usr/bin:/sbin:/usr/sbin
+NAME=kibana3
+DESC="Elasticsearch Server kibana3"
+DEFAULT=/etc/default/$NAME
+
+if [ `id -u` -ne 0 ]; then
+	echo "You need root privileges to run this script"
+	exit 1
+fi
+
+# Run Elasticsearch as this user ID and group ID
+ES_USER=elasticsearch
+ES_GROUP=elasticsearch
+
+# The first existing directory is used for JAVA_HOME (if JAVA_HOME is not defined in $DEFAULT)
+JDK_DIRS="/usr/lib/jvm/java-7-oracle /usr/lib/jvm/java-7-openjdk /usr/lib/jvm/java-7-openjdk-amd64/ /usr/lib/jvm/java-7-openjdk-armhf /usr/lib/jvm/java-7-openjdk-i386/ /usr/lib/jvm/java-6-sun /usr/lib/jvm/java-6-openjdk /usr/lib/jvm/java-6-openjdk-amd64 /usr/lib/jvm/java-6-openjdk-armhf /usr/lib/jvm/java-6-openjdk-i386 /usr/lib/jvm/default-java"
+
+# Look for the right JVM to use
+for jdir in $JDK_DIRS; do
+    if [ -r "$jdir/bin/java" -a -z "${JAVA_HOME}" ]; then
+        JAVA_HOME="$jdir"
+    fi
+done
+export JAVA_HOME
+
+# Directory where the Elasticsearch binary distribution resides
+ES_HOME=/usr/share/elasticsearch
+
+# Maximum number of open files
+MAX_OPEN_FILES=65535
+
+# Elasticsearch log directory
+LOG_DIR=/var/log/$NAME
+
+# Elasticsearch data directory
+DATA_DIR=/var/lib/$NAME
+
+# Elasticsearch work directory
+WORK_DIR=/tmp/$NAME
+
+# Elasticsearch configuration directory
+CONF_DIR=/etc/elasticsearch/$NAME
+
+# Elasticsearch configuration file (elasticsearch.yml)
+CONF_FILE=$CONF_DIR/elasticsearch.yml
+
+# Maximum number of VMA (Virtual Memory Areas) a process can own
+MAX_MAP_COUNT=262144
+
+
+# Define other required variables
+DAEMON=$ES_HOME/bin/elasticsearch
+DAEMON_OPTS="-Des.default.config=$CONF_FILE -Des.default.path.home=$ES_HOME -Des.default.path.logs=$LOG_DIR -Des.default.path.data=$DATA_DIR -Des.default.path.work=$WORK_DIR -Des.default.path.conf=$CONF_DIR"
+
+export ES_HEAP_SIZE
+export ES_HEAP_NEWSIZE
+export ES_DIRECT_SIZE
+export ES_JAVA_OPTS
+export ES_CLASSPATH
+
+checkJava() {
+	if [ -x "$JAVA_HOME/bin/java" ]; then
+		JAVA="$JAVA_HOME/bin/java"
+	else
+		JAVA=`which java`
+	fi
+
+	if [ ! -x "$JAVA" ]; then
+		echo "Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME"
+		exit 1
+	fi
+}
+
+checkJava
+
+
+# Prepare environment
+mkdir -p "$LOG_DIR" "$DATA_DIR" "$WORK_DIR" && chown "$ES_USER":"$ES_GROUP" "$LOG_DIR" "$DATA_DIR" "$WORK_DIR"
+touch "$PID_FILE" && chown "$ES_USER":"$ES_GROUP" "$PID_FILE"
+
+if [ -n "$MAX_OPEN_FILES" ]; then
+  ulimit -n $MAX_OPEN_FILES
+fi
+
+if [ -n "$MAX_LOCKED_MEMORY" ]; then
+   ulimit -l $MAX_LOCKED_MEMORY
+fi
+
+if [ -n "$MAX_MAP_COUNT" ]; then
+   sysctl -q -w vm.max_map_count=$MAX_MAP_COUNT
+fi
+
+# Start Daemon
+echo "$DAEMON $DAEMON_OPTS"
+$DAEMON $DAEMON_OPTS
